[package]
name = "aoc"
version = "0.1.0"
authors = ["KrishanBhasin <KrishanBhasin@users.noreply.github.com>"]
edition = "2018"
include = ["*.txt"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
